version: 2

models:
  - name: stg_free_company_data__freecompanydataset
    description: "Staged freecompanydataset from free_company_data — renamed columns, 1:1 with source"
    columns:
      - name: country
        description: ""
      - name: founded
        description: ""
      - name: id
        description: ""
        tests:
          - unique
          - not_null
      - name: industry
        description: ""
      - name: linkedin_url
        description: ""
      - name: locality
        description: ""
      - name: name
        description: ""
      - name: region
        description: ""
      - name: size
        description: ""
      - name: website
        description: ""
