-- =============================================================================
-- Snowflake Setup — Run this in Snowsight as ACCOUNTADMIN
-- Generated by bootstrap.sh on 2026-03-13
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- Database and schemas
CREATE DATABASE IF NOT EXISTS DBT_DEV;
CREATE SCHEMA IF NOT EXISTS DBT_DEV.DBT_STAGING;
CREATE SCHEMA IF NOT EXISTS DBT_DEV.DBT_INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS DBT_DEV.DBT_MARTS;
CREATE SCHEMA IF NOT EXISTS DBT_DEV.SEMANTIC;
CREATE SCHEMA IF NOT EXISTS DBT_DEV.SNAPSHOTS;

-- Internal stage for Cortex Analyst YAML semantic models
CREATE STAGE IF NOT EXISTS DBT_DEV.SEMANTIC.CORTEX_ANALYST_MODELS
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  COMMENT = 'Internal stage for Cortex Analyst YAML semantic models — upload via scripts/upload_semantic_model_to_stage.py';

-- Stored procedure for uploading YAML files to stage from Snowflake worksheets / Cortex Code
-- (PUT command only works from local clients, not from within Snowflake)
CREATE OR REPLACE PROCEDURE DBT_DEV.SEMANTIC.UPLOAD_YAML_TO_STAGE(
    STAGE_PATH VARCHAR,
    FILE_NAME VARCHAR,
    YAML_CONTENT VARCHAR
)
RETURNS VARCHAR
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('snowflake-snowpark-python')
HANDLER = 'main'
COMMENT = 'Upload a YAML file to an internal stage. Use when PUT is unavailable (e.g. Snowflake worksheets, Cortex Code).'
AS
$$
import io

def main(session, stage_path, file_name, yaml_content):
    input_stream = io.BytesIO(yaml_content.encode('utf-8'))
    session.file.put_stream(
        input_stream,
        f'{stage_path}/{file_name}',
        auto_compress=False,
        overwrite=True
    )
    return f'Successfully uploaded {file_name} to {stage_path}'
$$;

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS DBT_AGENT_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- Role with full permissions (for dbt build / model deployment)
CREATE ROLE IF NOT EXISTS DBT_ROLE;
GRANT ALL PRIVILEGES ON DATABASE DBT_DEV TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE DBT_DEV TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE DBT_DEV TO ROLE DBT_ROLE;
GRANT USAGE ON WAREHOUSE DBT_AGENT_WH TO ROLE DBT_ROLE;

-- Cortex Analyst Role — LEAST-PRIVILEGE for Copilot / Cortex Analyst / Intelligence
-- NEVER use ACCOUNTADMIN for Cortex sessions. Use this role instead.
-- Full setup: scripts/snowflake_cortex_rbac_setup.sql
CREATE ROLE IF NOT EXISTS CORTEX_ANALYST_ROLE
  COMMENT = 'Read-only role for Cortex Analyst, Copilot, and Snowflake Intelligence';
GRANT USAGE ON DATABASE DBT_DEV TO ROLE CORTEX_ANALYST_ROLE;
GRANT USAGE ON SCHEMA DBT_DEV.DBT_MARTS TO ROLE CORTEX_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEV.DBT_MARTS TO ROLE CORTEX_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEV.DBT_MARTS TO ROLE CORTEX_ANALYST_ROLE;
GRANT USAGE ON SCHEMA DBT_DEV.SEMANTIC TO ROLE CORTEX_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA DBT_DEV.SEMANTIC TO ROLE CORTEX_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DBT_DEV.SEMANTIC TO ROLE CORTEX_ANALYST_ROLE;
GRANT READ ON STAGE DBT_DEV.SEMANTIC.CORTEX_ANALYST_MODELS TO ROLE CORTEX_ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE DBT_AGENT_WH TO ROLE CORTEX_ANALYST_ROLE;

-- Role hierarchy: DBT_ROLE inherits CORTEX_ANALYST_ROLE
GRANT ROLE CORTEX_ANALYST_ROLE TO ROLE DBT_ROLE;

-- Source data (read-only) — IMPORTED PRIVILEGES works for Marketplace shared DBs
GRANT IMPORTED PRIVILEGES ON DATABASE COVID19_EPIDEMIOLOGICAL_DATA TO ROLE DBT_ROLE;
-- GRANT USAGE ON SCHEMA COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC TO ROLE DBT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC TO ROLE DBT_ROLE;

-- Assign roles to user
GRANT ROLE DBT_ROLE TO USER REGURAM;
-- For analysts who only need Cortex access (not dbt build):
-- GRANT ROLE CORTEX_ANALYST_ROLE TO USER <ANALYST_USER>;
-- ALTER USER <ANALYST_USER> SET DEFAULT_ROLE = 'CORTEX_ANALYST_ROLE';

-- =============================================================================
-- Snowflake Intelligence — Agent + SI object for Cortex Analyst NL querying
-- =============================================================================

-- Snowflake Intelligence object (account-level singleton for the SI UI)
-- Safe to run even if it already exists — will no-op on duplicate.
-- CREATE SNOWFLAKE INTELLIGENCE SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT;

-- Agent permissions (run AFTER creating agents via ddl/cortex-analyst/deploy_agent_*.sql)
-- GRANT USAGE ON AGENT DBT_DEV.SEMANTIC.AGENT_JAPAN_ECOMM TO ROLE DBT_ROLE;
-- GRANT READ ON STAGE DBT_DEV.SEMANTIC.CORTEX_ANALYST_MODELS TO ROLE DBT_ROLE;
-- GRANT USAGE ON SNOWFLAKE INTELLIGENCE SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT TO ROLE DBT_ROLE;

-- =============================================================================
-- Admin User — srikanth (ACCOUNTADMIN equivalent)
-- Run as ACCOUNTADMIN in Snowsight.
-- ACCOUNTADMIN is the highest-privilege system role in Snowflake.
-- Only grant it to users who genuinely need full account administration.
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- Create the user with a temporary password that must be changed on first login
CREATE USER IF NOT EXISTS srikanth
    DISPLAY_NAME    = 'srikanth'
    LOGIN_NAME      = 'srikanth'
    MUST_CHANGE_PASSWORD = TRUE
    -- Replace the placeholder below with the real temporary password before running.
    -- Password rules: ≥8 chars, 1 upper, 1 lower, 1 digit, 1 special character.
    PASSWORD        = '<REPLACE_WITH_TEMP_PASSWORD>'
    COMMENT         = 'Admin user — granted ACCOUNTADMIN';

-- Grant the ACCOUNTADMIN system role
GRANT ROLE ACCOUNTADMIN TO USER srikanth;

-- Also grant the project roles so the user can operate the dbt project
GRANT ROLE DBT_ROLE TO USER srikanth;
GRANT ROLE CORTEX_ANALYST_ROLE TO USER srikanth;

-- Set sensible defaults
ALTER USER srikanth SET
    DEFAULT_ROLE      = 'ACCOUNTADMIN'
    DEFAULT_WAREHOUSE = 'DBT_AGENT_WH';

-- Verify
SELECT
    NAME,
    LOGIN_NAME,
    DISPLAY_NAME,
    DEFAULT_ROLE,
    DEFAULT_WAREHOUSE,
    MUST_CHANGE_PASSWORD,
    HAS_PASSWORD,
    DISABLED
FROM SNOWFLAKE.ACCOUNT_USAGE.USERS
WHERE LOGIN_NAME = 'SRIKANTH';

-- =============================================================================
-- Verify
-- =============================================================================
SELECT 'Setup complete!' AS status;
