-- =============================================================================
-- Snowflake Setup — Run this in Snowsight as ACCOUNTADMIN
-- Generated by bootstrap.sh on 2026-03-13
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- Database and schemas
CREATE DATABASE IF NOT EXISTS DBT_DEV;
CREATE SCHEMA IF NOT EXISTS DBT_DEV.DBT_STAGING;
CREATE SCHEMA IF NOT EXISTS DBT_DEV.DBT_INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS DBT_DEV.DBT_MARTS;
CREATE SCHEMA IF NOT EXISTS DBT_DEV.SEMANTIC;
CREATE SCHEMA IF NOT EXISTS DBT_DEV.SNAPSHOTS;

-- Internal stage for Cortex Analyst YAML semantic models
CREATE STAGE IF NOT EXISTS DBT_DEV.SEMANTIC.CORTEX_ANALYST_MODELS
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  COMMENT = 'Internal stage for Cortex Analyst YAML semantic models — upload via scripts/upload_semantic_model_to_stage.py';

-- Stored procedure for uploading YAML files to stage from Snowflake worksheets / Cortex Code
-- (PUT command only works from local clients, not from within Snowflake)
CREATE OR REPLACE PROCEDURE DBT_DEV.SEMANTIC.UPLOAD_YAML_TO_STAGE(
    STAGE_PATH VARCHAR,
    FILE_NAME VARCHAR,
    YAML_CONTENT VARCHAR
)
RETURNS VARCHAR
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('snowflake-snowpark-python')
HANDLER = 'main'
COMMENT = 'Upload a YAML file to an internal stage. Use when PUT is unavailable (e.g. Snowflake worksheets, Cortex Code).'
AS
$$
import io

def main(session, stage_path, file_name, yaml_content):
    input_stream = io.BytesIO(yaml_content.encode('utf-8'))
    session.file.put_stream(
        input_stream,
        f'{stage_path}/{file_name}',
        auto_compress=False,
        overwrite=True
    )
    return f'Successfully uploaded {file_name} to {stage_path}'
$$;

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS DBT_AGENT_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- Role with full permissions
CREATE ROLE IF NOT EXISTS DBT_ROLE;
GRANT ALL PRIVILEGES ON DATABASE DBT_DEV TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE DBT_DEV TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE DBT_DEV TO ROLE DBT_ROLE;
GRANT USAGE ON WAREHOUSE DBT_AGENT_WH TO ROLE DBT_ROLE;

-- Source data (read-only) — IMPORTED PRIVILEGES works for Marketplace shared DBs
GRANT IMPORTED PRIVILEGES ON DATABASE COVID19_EPIDEMIOLOGICAL_DATA TO ROLE DBT_ROLE;
-- GRANT USAGE ON SCHEMA COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC TO ROLE DBT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC TO ROLE DBT_ROLE;

-- Assign role to user
GRANT ROLE DBT_ROLE TO USER REGURAM;

-- Verify
SELECT 'Setup complete!' AS status;
