version: 2

models:
  - name: stg_japan_ecomm_data__mall_markets_monthly_transaction
    description: "Staged mall_markets_monthly_transaction from japan_ecomm_data — renamed columns, 1:1 with source"
    columns:
      - name: listing_id
        description: ""
        tests:
          - unique
          - not_null
      - name: website_type
        description: ""
      - name: data_source
        description: ""
      - name: sales_date
        description: ""
      - name: maker
        description: ""
      - name: item_name
        description: ""
      - name: model
        description: ""
      - name: release_date
        description: ""
      - name: condition
        description: ""
      - name: volume
        description: ""
      - name: is_sim_free
        description: ""
      - name: network_restriction
        description: ""
      - name: price
        description: ""
      - name: stock_period
        description: ""
  - name: stg_japan_ecomm_data__mall_markets_yearly_report
    description: "Staged mall_markets_yearly_report from japan_ecomm_data — renamed columns, 1:1 with source"
    columns:
      - name: month
        description: ""
      - name: website_type
        description: ""
      - name: data_source
        description: ""
      - name: maker
        description: ""
      - name: item_name
        description: ""
      - name: model
        description: ""
      - name: release_date
        description: ""
      - name: condition
        description: ""
      - name: volume
        description: ""
      - name: sum_price
        description: ""
      - name: mom_change_in_listing_count
        description: ""
      - name: transaction_ount
        description: ""
      - name: mom_change_in_transaction_count
        description: ""
      - name: listing_count
        description: ""
      - name: mom_change_in_gmv
        description: ""
